version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: map-search-proxy
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://root:super_secret@mongodb:27017/map-search?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: super_secret
    networks:
      - app-network

networks:
  app-network:
    driver: bridge